/**
 * Portfolio component
 *
 * Highlights some of  your creations. These can be designs, websites,
 * open source contributions, articles you've written and more.
 *
 * This is a great area for you to to continually add to and refine
 * as you continue to learn and create.
 */

import React from "react";

/**
 * Desk image
 *
 * Below is a sample desk image.
 */
import image from "../images/portfolio_image.jpg";

const imageAltText = "An image generated by an AI related to the portfolio of a student of artificial intelligence engineering";

/**
 * Project list
 *
 * An array of objects that will be used to display for project
 * links section.
 */
const projectList = [
  {
    title: "Faculty Management for the School of Computer Science",
    description:
      "Collaboration to create a beginner friendly article to help explain Azure Static Web Apps and tooling to get started.",
    url: "https://github.com/Ricardo8421/crujirepo",
  },
  {
    title: "Projects and assignments completed during my time at ESCOM",
    description:
      "Contributed sketch note imagery to accompany each lesson. These help provide visual representation of what is being taught.",
    url: "",
  },
  {
    title: "My Resume Site",
    description:
      "Created from GitHub Education's project templates and deployed to GitHub pages. Includes my experience,education and design abilities.",
    url: "https://oscarjuji.github.io/Portafolio/",
  },
  {
    title: "A basic program featuring a graphical interface of identifying object contours and classifying",
    description:
      "This project was completed within a team setting for the digital image processing course. The aim was to create a Matlab program that could identify object edges in a natural setting image and, in a basic manner, classify them to ascertain the image's corresponding environment.",
    url: "",
  },
];

const Portfolio = () => {
  return (
    <section className="padding" id="portfolio">
      <h2 style={{ textAlign: "center" }}>Portfolio</h2>
      <div style={{ display: "flex", flexDirection: "row", paddingTop: "3rem" }}>
        <div style={{ maxWidth: "40%", alignSelf: "center" }}>
          <img
            src={image}
            style={{ height: "90%", width: "100%", objectFit: "cover" }}
            alt={imageAltText}
          />
        </div>
        <div className="container">
          {projectList.map((project) => (
            <div className="box" key={project.title}>
              <a href={project.url} target="_blank" rel="noopener noreferrer">
                <h3 style={{ flexBasis: "40px" }}>{project.title}</h3>
              </a>
              <p className="small">{project.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
