/**
 * Portfolio component
 *
 * Highlights some of  your creations. These can be designs, websites,
 * open source contributions, articles you've written and more.
 *
 * This is a great area for you to to continually add to and refine
 * as you continue to learn and create.
 */

import React from "react";

/**
 * Desk image
 *
 * Below is a sample desk image.
 */
import image from "../images/image.webp";

const imageAltText = "An image generated by an AI related to the portfolio of a student of artificial intelligence engineering";

/**
 * Project list
 *
 * An array of objects that will be used to display for project
 * links section.
 */
const projectList = [
  {
    title: "HomeCraft. A desktop app for creating and editing independent 3D models for interior design and decoration.",
    description:
      "HomeCraft is an AI-driven project that allows users to capture a video of their room, extract key frames, segment objects, apply inpainting, and generate a fully editable 3D model of their space. The goal is to enable seamless virtual home redesigns without physically modifying the real-world environment.",
    url: "https://github.com/PhilipSanM/Homecraft",
  },
  {
    title: "RAG ChatBot",
    description:
      "A web application for asking questions in natural language about the Mexican DOF. Collaboratively developed a Retrieval Augmented Generation (RAG) for a Large Language Model (LLM) to generate resumes and respond to natural language queries about the Mexican Official Diary of the Federation (DOF).",
    url: "https://github.com/JoseLuisMonroy/ISSI-Backend",
  },
  {
    title: "Genetic Algorithm Sudoku Solver",
    description:
      "Developed a Genetic Algorithm capable of solving hard-level Sudoku puzzles 20% faster than some initial state-of-the-art approaches. The algorithm leverages evolutionary strategies, including selection, crossover, and mutation, to efficiently explore the solution space and optimize performance.",
    url: "https://oscarjuji.github.io/Portfolio/",
  },
  {
    title: "Student Management System ",
    url: "https://github.com/Ricardo8421/crujirepo",
  },
  {
    title: "A basic program featuring a graphical interface of identifying object contours and classifying",
    description:
      "This project was completed within a team setting for the digital image processing course. The aim was to create a Matlab program that could identify object edges in a natural setting image and, in a basic manner, classify them to ascertain the image's corresponding environment.",
    url: "https://github.com/OscarJuJi/object_contours_identifiying_and_classifying",
    title: "Projects and assignments completed during my time at ESCOM",
    description:
      "This repository showcases a collection of projects and assignments completed during my time at ESCOM as part of the Artificial Intelligence Engineering program. The work reflects a broad range of skills—from data structures and software engineering to computer vision, neural networks, deep learning and various other topics.",
    url: "https://github.com/OscarJuJi",
  },
];

const Portfolio = () => {
  return (
    <section className="padding" id="portfolio">
      <h2 style={{ textAlign: "center" }}>Portfolio</h2>
      <div style={{ display: "flex", flexDirection: "row", paddingTop: "3rem" }}>
        <div style={{ maxWidth: "40%", alignSelf: "center" }}>
          <img
            src={image}
            style={{
              height: "90%",
              width: "100%",
              objectFit: "cover",
              animation: "1s ease-out 0s 1 slideIn",
            }}
            alt={imageAltText}
          />
        </div>
        <div className="container">
          {projectList.map((project) => (
            <div className="box" key={project.title} style={{background:"#eeeedcaa"}}>
              <a href={project.url} target="_blank" rel="noopener noreferrer">
                <h3 style={{ flexBasis: "40px" }}>{project.title}</h3>
              </a>
              <p className="small">{project.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
